
version: '2.1'
services:
  #docker-compose build image
  image:
    build:
      context: .
      dockerfile: Dockerfile
      args:
      - IMAGE_ARG_ALPINE_MIRROR=${IMAGE_ARG_ALPINE_MIRROR:-mirror.tuna.tsinghua.edu.cn}

      - IMAGE_ARG_ENCODING=${IMAGE_ARG_ENCODING:-UTF-8}
      #- IMAGE_ARG_JAVA_LD_LIBRARY_PATH=${IMAGE_ARG_JAVA_LD_LIBRARY_PATH:-/usr/glibc-compat/lib}
      - IMAGE_ARG_JAVA_OPTS=${IMAGE_ARG_JAVA_OPTS}
      #- IMAGE_ARG_JAVA_VERSION=${IMAGE_ARG_JAVA_VERSION:-9.0.4}
      - IMAGE_ARG_LANGUAGE=${IMAGE_ARG_LANGUAGE:-en}
      - IMAGE_ARG_LOCALE=${IMAGE_ARG_LOCALE:-en_US}
      - IMAGE_ARG_REGION=${IMAGE_ARG_REGION:-US}
      - IMAGE_ARG_JAVA_HOME=${IMAGE_ARG_JAVA_HOME:-/usr/lib/jvm/java-9-oracle}
      #- IMAGE_ARG_TZ=${IMAGE_ARG_TZ:-UTC+8:00}
      - IMAGE_ARG_TZ_AREA=${IMAGE_ARG_TZ_AREA:-Etc}
      - IMAGE_ARG_TZ_ZONE=${IMAGE_ARG_TZ_ZONE:-UTC}
    image: ${IMAGE_PREFIX:-cirepo}/${IMAGE_NAME:-java-oracle}:${IMAGE_TAG:-9.0.4-en_US.UTF-8_Etc.UTC-alpine}
